/*
 * generated by Xtext 2.14.0
 */
package com.example.helloweb.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link MyDslWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractMyDslWebModule extends DefaultWebModule {

}
