/*
 * generated by Xtext 2.14.0
 */
package com.example.helloweb.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MyDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/example/helloweb/parser/antlr/internal/InternalMyDsl.tokens");
	}
}
