/*
 * generated by Xtext 2.14.0
 */
package com.example.helloweb.ui;

import com.example.helloweb.ui.internal.HellowebActivator;
import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(HellowebActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		HellowebActivator activator = HellowebActivator.getInstance();
		return activator != null ? activator.getInjector(HellowebActivator.COM_EXAMPLE_HELLOWEB_MYDSL) : null;
	}

}
