/**
 * generated by Xtext 2.14.0
 */
package com.example.helloweb.ui;

import com.example.helloweb.ui.AbstractMyDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MyDslUiModule extends AbstractMyDslUiModule {
  public MyDslUiModule(final AbstractUIPlugin arg0) {
    super(arg0);
  }
}
