/**
 * generated by Xtext 2.14.0
 */
package com.example.helloweb.web;

import com.example.helloweb.MyDslRuntimeModule;
import com.example.helloweb.MyDslStandaloneSetup;
import com.example.helloweb.ide.MyDslIdeModule;
import com.example.helloweb.web.MyDslWebModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class MyDslWebSetup extends MyDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    MyDslRuntimeModule _myDslRuntimeModule = new MyDslRuntimeModule();
    MyDslIdeModule _myDslIdeModule = new MyDslIdeModule();
    MyDslWebModule _myDslWebModule = new MyDslWebModule();
    return Guice.createInjector(Modules2.mixin(_myDslRuntimeModule, _myDslIdeModule, _myDslWebModule));
  }
}
