/**
 * generated by Xtext 2.14.0
 */
package com.example.helloweb.web;

import com.example.helloweb.web.AbstractMyDslWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class MyDslWebModule extends AbstractMyDslWebModule {
}
