/*
 * generated by Xtext 2.14.0
 */
package com.example.helloweb.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractMyDslValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(com.example.helloweb.myDsl.MyDslPackage.eINSTANCE);
		return result;
	}
}
