/*
 * generated by Xtext 2.14.0
 */
package com.example.helloweb.ide

import com.example.helloweb.MyDslRuntimeModule
import com.example.helloweb.MyDslStandaloneSetup
import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MyDslIdeSetup extends MyDslStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MyDslRuntimeModule, new MyDslIdeModule))
	}
	
}
