/**
 * generated by Xtext 2.14.0
 */
package com.example.helloweb.ide;

import com.example.helloweb.ide.AbstractMyDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MyDslIdeModule extends AbstractMyDslIdeModule {
}
